version: '3.8'

services:
  # 1. Base de datos Logiflow
  postgres-db:
    image: postgres:15-alpine
    container_name: logiflow-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - logiflow-network

  # 2. Broker de Mensajeria (RabbitMQ) 
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: logiflow-rabbitmq
    ports:
      - "5672:5672"   # Puerto para comunicacion entre microservicios
      - "15672:15672" # Puerto para el Panel Visual (Entrar con guest/guest)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - logiflow-network

  # 3. Kong Gateway (Base de datos)
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    volumes:
      - kong_data:/var/lib/postgresql/data
    networks:
      - logiflow-network

  # 4. Kong Migration (Inicializador)
  kong-migration:
    image: kong:latest
    container_name: kong-migration
    command: "kong migrations bootstrap"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
    depends_on:
      - kong-database
    networks:
      - logiflow-network

  # 5. Kong Gateway (Servicio Principal)
  kong:
    image: kong:latest
    container_name: kong-gateway
    restart: always
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - kong-migration
    networks:
      - logiflow-network

  # 6. Base de datos para Konga (MongoDB)
  mongo:
    image: mongo:4.2
    container_name: konga-mongo
    networks:
      - logiflow-network
    volumes:
      - konga_mongo_data:/data/db

  # 7. Panel Visual Konga
  konga:
    image: pantsel/konga
    container_name: konga-ui
    restart: always
    environment:
      DB_ADAPTER: mongo
      DB_URI: mongodb://mongo:27017/konga
      NODE_ENV: development
    ports:
      - "1337:1337"
    depends_on:
      - mongo  
    networks:
      - logiflow-network

volumes:
  postgres_data:
  kong_data:
  konga_mongo_data: 
  rabbitmq_data: 

networks:
  logiflow-network:
    driver: bridge