apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      hostAliases:
      - ip: "192.168.49.1" 
        hostnames:
        - "host.minikube.internal"
      containers:
      - name: notification-service
        image: erickvinu/notification-service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        # BASE DE DATOS
        - name: DB_HOST
          value: "host.minikube.internal"
        - name: DB_PORT
          value: "5433"
        - name: DB_NAME
          value: "db_notifications"
        
        # RABBITMQ 
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@host.minikube.internal:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: LoadBalancer # Para poder conectar el Frontend despu√©s
  selector:
    app: notification-service
  ports:
    - port: 3001
      targetPort: 3001